### ISSUE TITLE
Epic problems with refactor-build branch

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#266]
- [x] A bunch of APIs were missing caused by 5 symbols not defined for .NET Framework like they used to be (#265)
- [x] Assemblies didn't used to define the `AssemblyTitleAttribute`, I don't have a problem with it other than it being the same for each assembly which turns out to be wrong since that describes Castle.Core.dll but not the others.
  - `AssemblyTitleAttribute("Castle Project Core, including DynamicProxy, Logging Abstractions and DictionaryAdapter")`
- [x] `AssemblyDescriptionAttribute` didn't used to be defined, it is currently got the following garbage value:
  - `AssemblyDescriptionAttribute("Package Description")`
- [x] ~~AppVeyor builds for Windsor produce versions like `0.0.37-nrtymivf` for pull requests, we've got it set not to increment the build number for pull requests, we should do the same for Castle Core.~~ Windsor will match versioning scheme in Castle Core. 
- [x] AppVeyor builds are publishing a package for unit tests:
  - build\Castle.Core.Tests.0.0.56.nupkg
  - build\Castle.Core.Tests.0.0.56.symbols.nupkg
- [x] The logging integration package names have changed, they used be e.g. `Castle.Core-Serilog` but are now e.g. `Castle.Services.Logging.SerilogIntegration` after their assembly name.
- [x] NuGet tags have not been set. 
- [x] NuGet id's create different package names which break appveyor for tag based releases in the build output directory. 
- [x] NuGet authors tag is wrong, it says Castle Contributors, should be Castle Project Contributors.

BitDiffer kept crashing on .NET Standard assemblies, I'll have to find something else to look at this again.

**Comment by jonorossi** [comment]
@fir3pho3nixx did you want to tackle these ones?

**Comment by fir3pho3nixx** [comment]
@jonorossi - more than happy to. 

`AssemblyTitleAttribute` - will move these down into the constituent projects. 

`AssemblyDescriptionAttribute` - you OK for this to be removed?

`0.0.37-nrtymivf` - I don't like this at all. Your tag names conventionally override this anyway using [semver](https://github.com/castleproject/Core/blob/refactor-build/appveyor.yml#L23). So you still have control regardless. If you feel strongly about this we can revisit. 

 `build\Castle.Core.Tests.0.0.56.nupkg` - This would never be published anyway because of [this](https://github.com/castleproject/Core/blob/refactor-build/appveyor.yml#L36) but you are right, we should clean this up. Was hoping [this](https://github.com/castleproject/Core/blob/refactor-build/src/Castle.Core.Tests/Castle.Core.Tests.csproj#L18) would have some effect alas it does not.

`Castle.Core-Serilog` - Thought I checked and triple checked this. Think I will do a complete review of NuGet id's. Sorry about this. 

God damn it! It is good to have working internet again :)

**Comment by fir3pho3nixx** [comment]
@jonorossi - Please assign me to this issue.

**Comment by jonorossi** [comment]
> AssemblyTitleAttribute - will move these down into the constituent projects.

👍 

> AssemblyDescriptionAttribute - you OK for this to be removed?

👍 

> 0.0.37-nrtymivf - I don't like this at all. Your tag names conventionally override this anyway using semver. So you still have control regardless. If you feel strongly about this we can revisit.

I just wanted Core and Windsor to behave the same, I don't mind which one changes as they'll all get 0.0.x versions unless being tagged.

> build\Castle.Core.Tests.0.0.56.nupkg - This would never be published anyway because of this but you are right, we should clean this up. Was hoping this would have some effect alas it does not.

👍 

> Castle.Core-Serilog - Thought I checked and triple checked this. Think I will do a complete review of NuGet id's. Sorry about this.

No problem, much easier to catch these things now.

> God damn it! It is good to have working internet again :)

Maybe don't live in 🇦🇺  then, our internet sucks everyday 😉 

> Please assign me to this issue.

I've granted you ✍️  permissions on Core, you can assign the issue to yourself!

**Comment by fir3pho3nixx** [comment]
Going to edit tasks in this issue before I submit my PR ...

**Comment by fir3pho3nixx** [comment]
I have trawled through the meta-data for the NuGet packages. The only difference I can see is that we no longer do `summary` and we have an f-ton less dependencies. 

![image](https://user-images.githubusercontent.com/607402/26851720-995cf366-4b03-11e7-80f1-e2af699597cf.png)

More review would not hurt. Thanks for checking this.

**Comment by fir3pho3nixx** [comment]
> Maybe don't live in :australia: then, our internet sucks everyday 😉

:south_africa: is worse, was moaning to my sister about having my transitional line with BT @ 2mbps with persistent line reset's every 5-10 minutes and she was telling me that is awesome compared to what they got. Think you guys got some latency in Oz. I am now on fibre. It changed my life :)

**Comment by jonorossi** [comment]
> I have trawled through the meta-data for the NuGet packages. The only difference I can see is that we no longer do summary and we have an f-tonne less dependencies.

Heaps less dependencies however we have picked up `NETStandard.Library`. I'll take a deeper look again later today. Thanks heaps for getting this all sorted.

> Think you guys got some latency in Oz

Yep. I complain but it really isn't that bad, no dropouts, hopefully I'll have fibre someday when the NBN gets to us.

**Comment by jonorossi** [comment]
Love the new issue title 👍

**Comment by fir3pho3nixx** [comment]
@jonorossi - I looked into the `NETStandard.Library`, it looks like this is a meta package or aggregate package which groups common framework api's together for various framework targets. I think this is why we have seen a reduction in our dependencies. I am going to start digging into the `build-refactor` branch in windsor and rinse and repeat some of the work we have done here.

**Comment by fir3pho3nixx** [comment]
@jonorossi - I did a clean sweep of Castle Windsor, and I must say it is looking good also the version numbering works exactly the same as it does in core. 

> Love the new issue title 👍

It would have been a cock up if we released it in that state :)

**Comment by fir3pho3nixx** [comment]
You cannot do strike through's in issue titles? Oh well ...

**Comment by fir3pho3nixx** [comment]
Yeay!
